name: build simple ssh client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare
      run: |
        sudo apt-get install -y libssh2-1-dev
        
    - name: make
      run: make
